name: Render PlantUML
on: push
jobs:
  render_plantuml:
    runs-on: ubuntu-latest
    name: Render PlantUML
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Render PlantUML
      id: plantuml
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: src/diagrams/generated
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
